### PR TITLE
chore(json-schemer): update the json schemer gem to latest version

### PR DESCRIPTION
**Pull request by bchaney**
Update `json_schemer` to the latest version to get the most up to date JSON Schemas, ie: `https://json-schema.org/draft/2020-12/schema`

https://app.asana.com/0/1205843647973060/1206121259471910/f

### CODE REVIEW

**Comment by bchaney** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1** <a href="https://app.graphite.dev/github/pr/instrumentl/activerecord_json_validator/1?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/instrumentl/activerecord_json_validator/1?utm_source=stack-comment).

**Comment by Roguelazer** [comment]
It looks like the test suite doesn't work due to https://github.com/mirego/activerecord_json_validator/pull/74, so we may have to do some manual testing to see if this works

**Review by bchaney — COMMENTED** [review]
@Roguelazer I have tested this locally. Updating to the 2020-12 schema will error before and work correctly now

**Comment by bchaney** [comment]
Well for calendar urls at least

**Pull request merged**
